rm -f tdp_sk.key
rm -f derivation_master.key
rm -f tdp_pk.key
rm -f client.csv
rm -rf client.sav
rm -rf server.dat*
rm -f tdp_sk2.key
rm -f derivation_master2.key
rm -f tdp_pk2.key
rm -f client2.csv
rm -rf client2.sav
rm -rf server2.dat
rm -rf diana_client_*
rm -rf diana_server_*
rm -rf diana_remote_server_*
rm -rf diana_derivation_master.key
rm -rf diana_kw_token_master.key
rm -rf janus_client.add.dat*
rm -rf janus_client.del.dat*
rm -rf janus_client.search.dat*
rm -rf janus_server.add.dat*
rm -rf janus_server.cache.dat*
rm -rf janus_server.del.dat*
rm -rf janus_master.key*
rm -rf mitra